version: '3'
services:

  stocky-frontend:
    build: .
    image: aktasberk/stocky-l-fe:v.0.5
    ports:
      - 8080:8080

  auth-service:
    image: aktasberk/stockylite-auth:v.0.1
    environment:
      config_url: http://config-server:8888
      java9secretkey: "12345"
      java9issuer: "basarsoft"
      java9audience: "auth_service_tekrar"
    depends_on:
      - config-server
    ports:
      - 9090:9090


  category-service:
    depends_on:
      - config-server
    image: aktasberk/stockylite-category:v.0.1
    environment:
      config_url: http://config-server:8888
    ports:
      - 9093:9093


  product-service:
    depends_on:
      - config-server
    image: aktasberk/stockylite-product:v.0.1
    environment:
      config_url: http://config-server:8888
    ports:
      - 9092:9092


  storage-service:
    depends_on:
      - config-server
    image: aktasberk/stockylite-storage:v.0.1
    environment:
      config_url: http://config-server:8888
    ports:
      - 9094:9094

  unit-service:
    depends_on:
      - config-server
    image: aktasberk/stockylite-unit:v.0.1
    environment:
      config_url: http://config-server:8888
    ports:
      - 9095:9095


  user-service:
    depends_on:
      - config-server
    image: aktasberk/stockylite-user:v.0.1
    environment:
      config_url: http://config-server:8888
      java9secretkey: 12345
      java9issuer: basarsoft
      java9audience: auth_service_tekrar
    ports:
      - 9091:9091


  config-server:
    image: aktasberk/stocky-l-config-server:v.0.6
    environment:
      config_url: http://config-server:8888
    ports:
      - 8888:8888


  api-gateway-service:
    depends_on:
      - config-server
    image: aktasberk/stockylite-api-gateway:v.0.1
    environment:
      config_url: http://config-server:8888
    ports:
      - 80:80

  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "user"
    ports:
      - "15672:15672"
      - "5672:5672"
