apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-apigateway
spec:
  replicas: 1
  selector:
    matchLabels: 
      team: developer-apigateway
  template:
    metadata:
      name: pod-apigateway
      labels:
        team: developer-apigateway
    spec:
      containers:
      - name: container-apigateway
        image: aktasberk/stocky-mastermind-api-gateway:v.0.1
        resources:
          limits:
            cpu: "500m"
            memory: "1024Mi"
        ports:
        - containerPort: 8080
        env:
        - name: config_url
          value: "http://10.12.13.92:8888"
        - name: java9gitconfigpassword
          value: 123        