apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-storage
spec:
  replicas: 1
  selector:
    matchLabels: 
      team: developer-storage
  template:
    metadata:
      name: pod-storage
      labels:
        team: developer-storage
    spec:
      containers:
      - name: container-storage
        image: aktasberk/stocky-mastermind-storage:v.0.1
        resources:
          limits:
            cpu: "400m"
            memory: "1024Mi"
        ports:
        - containerPort: 9094
        env:
        - name: config_url
          value: "http://10.12.13.92:8888"