apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-apigateway
spec:
  replicas: 1
  selector:
    matchLabels: 
      team: developer-apigateway
  template:
    metadata:
      name: pod-apigateway
      labels:
        team: developer-apigateway
    spec:
      containers:
      - name: container-apigateway
        image: aktasberk/stocky-api-gateway:v.0.16
        resources:
          limits:
            cpu: "300m"
            memory: "1024Mi"
        ports:
        - containerPort: 80
        env:
        - name: config_url
          value: "http://10.116.10.43:8888"
        - name: java9gitconfigpassword
          value: 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        