apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth
spec:
  replicas: 1
  selector:
    matchLabels: 
      team: developer-auth
  template:
    metadata:
      name: pod-auth
      labels:
        team: developer-auth
    spec:
      containers:
      - name: container-auth
        image: aktasberk/stocky-auth:v.0.2
        resources:
          limits:
            cpu: "150m"
            memory: "1024Mi"
        ports:
        - containerPort: 9090
        env:
        - name: config_url
          value: "http://10.116.10.43:8888"
        - name: java9secretkey
          value: "java9_secretkey"
        - name: java9issuer
          value: "basarsoft"
        - name: java9audience
          value: "auth"