apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-product
spec:
  replicas: 1
  selector:
    matchLabels: 
      team: developer-product
  template:
    metadata:
      name: pod-product
      labels:
        team: developer-product
    spec:
      containers:
      - name: container-product
        image: aktasberk/stocky-product:v.0.4
        resources:
          limits:
            cpu: "400m"
            memory: "1024Mi"
        ports:
        - containerPort: 9092
        env:
        - name: config_url
          value: "http://10.116.10.43:8888"