apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels: 
      team: developer-rabbitmq
  template:
    metadata:
      name: pod-rabbitmq
      labels:
        team: developer-rabbitmq
    spec:
      containers:
      - name: container-rabbitmq
        image: rabbitmq
        resources:
          limits:
            cpu: "200m"
            memory: "1024Mi"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: Aa123456**