apiVersion: v1
kind: Service
metadata:
  name: load-balancer-apigateway
spec:
  selector:
    team: developer-apigateway
  type: LoadBalancer
  ports:
  - name: otherports
    port: 80
    targetPort: 80