apiVersion: v1
kind: Service
metadata:
  name: clusterip-configservergit
spec:
  selector:
    team: developer-configservergit
  type: ClusterIP
  ports:
  - name: configservergit
    port: 8888
    targetPort: 8888