apiVersion: v1
kind: Service
metadata:
  name: clusterip-rabbitmq
spec:
  selector:
    team: developer-rabbitmq
  type: ClusterIP
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672
  - name: rabbitmq-web
    port: 15672
    targetPort: 15672