server:
  port: 9092

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:stocky.db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user




rabbitmq:
  category-id-queue: categoryIdQueue
  productExchange: productExchange
  storage-id-queue: StorageIdQueue
  unit-id-queue: unitIdQueue


feign:
  category: http://localhost:9093/api/v1/category
  storage: http://localhost:9094/api/v1/storage
  unit: http://localhost:9095/api/v1/unit
