server:
  port: 9094

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:stocky.db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user





rabbitmq:
  exchangeStorage: exchangeStorage
  storage-id-queue: StorageIdQueue
  storage-id-bindingKey: StorageIdBindingKey


feign:
