server:
  port: 9091

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:stocky.db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user


jwt:
  secretKey: ${java9secretkey}
  issuer: ${java9issuer}
  audience: ${java9audience}


rabbitmq:
  userExchange: userExchange
  register-user-queue: registerUserQueue
  delete-user-queue: deleteUserQueue
  delete-user-bindingKey: deleteUserBindingKey


feign:
  auth: http://localhost:9090/api/v1/auth
