apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer-stockyfe
spec:
  selector:
    app: developer-stockyfe
  type: LoadBalancer
  ports:
  - name: stockyfe
    port: 80
    targetPort: 80